#Capstone Config
version: 2.1

executors:
  docker:
    docker:
      - image: docker
  python:
    docker:
      - image: python:3.7.3-stretch
  aws:
    docker:
      - image: amazon/aws-cli

jobs:
  lintapp:
    executor: python
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            make install
      - run:
          name: run lint
          command: |
            make lint

workflows:
  deployment:
    jobs:
      - lintapp